server:
  port: 7778

dubbo:
  application:
    # 应用名称
    name: enter-exam-consumer
  # dubbo 多注册中心配置
  registries:
    # 注册中心名称
    userRegistry:
      # 注册中心地址 user
      address: zookeeper://47.96.154.148:2181
      default: true
      timeout: 600000
    enterExamRegistry:
      # 注册中心地址 yzw
      address: zookeeper://211.159.223.185:2182
      default: false
      timeout: 600000

  consumer:
    timeout: 600000

spring:
  redis:
    host: 120.46.166.53
    port: 6379
    password: Eeeee-11111
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 604800
#  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
#  is-concurrent: true
#  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
#  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 不采用token续签
  auto-renew: false
  # 不从请求体里读取token
  is-read-body: false
  # 不从cookie里读取token
  is-read-cookie: false

ignored: |
  /error,
  /user/stu/register,/user/tea/register,/user/sendCode,/user/getSchoolList,/user/login,/user/loginByCode,/user/updatePassword,/user/validateCode



