dubbo:
  application:
    # 应用名称
    name: marking-provider
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: -1
  consumer:
    timeout: 600000
  provider:
    filter: -exception
  registries:
    # 注册中心名称
    markingRegistry:
      # 注册中心地址
      address: zookeeper://101.35.52.77:2182
      default: true
      timeout: 600000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.165.47:3306/qgexam?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: Eeeee11111

  # redis配置
  redis:
    host: 120.46.166.53
    port: 6379
    password: Eeeee-11111
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启下划线和驼峰命名自动转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 逻辑删除字段自动处理
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键自增
      id-type: auto
  # mapper文件位置
  mapper-locations: classpath*:/mapper/**/*.xml


oss:
  accessKey: QrsCXu18PoWhOIGDIa5Ufej0pWLIKNfieQ3CpbGp
  secretKey: ZvqIjeQGEqGs3NyN8ChydWwlJEXbw_GddeLQ26hN
  bucket: my-blog11
  ossUrl: http://rjmbc6tzh.bkt.clouddn.com/



